---
- name: Reload systemd
  systemd:
    daemon_reload: yes
  become: yes
  when: ansible_virtualization_type != 'docker'

- name: Restart besu
  service:
    name: besu
    state: restarted
  become: yes
  when: ansible_virtualization_type != 'docker'
