---
cluster_cidr: 10.10.20.0/24
chrony_primary_host: validator-1
chrony_primary_ip: 10.10.20.11

besu_version: "24.12.0"
besu_tarball_checksum: "sha256:74d20b2a4b3da659f608d65c09ab95d2187dc2c54372d9f7330bf5190d5e7124"
besu_chain_id: 1337
besu_block_period_seconds: 2
besu_request_timeout_seconds: 4
besu_expected_validator_count: 4

node_exporter_port: 9100
process_exporter_port: 9256
besu_metrics_port: 9545

