---
- name: Wait for VMs to boot and SSH to become available
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH port 22 to open
      wait_for:
        port: 22
        host: "{{ ansible_host }}"
        search_regex: OpenSSH
        delay: 5
        timeout: 300
      delegate_to: localhost

- name: Prep baseline system configurations and TLS credentials
  hosts: all
  gather_facts: yes
  roles:
    - system_prep
    - tls_distributor

- name: Deploy, configure, and boot Hyperledger Besu nodes
  hosts: all
  gather_facts: yes
  roles:
    - besu_node
