#!/usr/bin/env python3
"""
detect_network.py — Local LAN Detection for IAC Besu
-----------------------------------------------------
Determines whether the current deployment is running in a local network
environment where binary caching would be beneficial.

Detection logic:
  1. All VM IPs in settings.yml are RFC-1918 private addresses (always true
     for this setup, but rules out external/cloud deployments).
  2. A quick latency probe to github.com to gauge internet speed.
     RTT > SLOW_THRESHOLD_MS  →  internet is slow  →  recommend caching.
     If github.com is unreachable at all we also recommend caching.

Outputs a JSON object to stdout consumed by run_all.sh:
  {"is_lan": true, "internet_rtt_ms": 312, "recommend_cache": true, "reason": "..."}

Also handles the sticky-prompt logic when called with --update-settings:
  python3 detect_network.py --update-settings true|false
  Updates config/settings.yml optimization.local_cache in-place.
"""

import json
import os
import re
import socket
import subprocess
import sys
import time
from pathlib import Path

# ── Tunables ──────────────────────────────────────────────────────────────────
SLOW_THRESHOLD_MS = 150   # RTT above this → recommend cache
PROBE_HOST        = "github.com"
PROBE_PORT        = 443
PROBE_TIMEOUT_S   = 4
RFC1918_RANGES    = [
    (0x0A000000, 0xFF000000),   # 10.0.0.0/8
    (0xAC100000, 0xFFF00000),   # 172.16.0.0/12
    (0xC0A80000, 0xFFFF0000),   # 192.168.0.0/16
]

REPO_ROOT    = Path(__file__).resolve().parent.parent
SETTINGS_YML = REPO_ROOT / "config" / "settings.yml"

# ── Helpers ───────────────────────────────────────────────────────────────────

def _ip_to_int(ip: str) -> int:
    parts = [int(x) for x in ip.split(".")]
    return (parts[0] << 24) | (parts[1] << 16) | (parts[2] << 8) | parts[3]


def is_rfc1918(ip: str) -> bool:
    try:
        n = _ip_to_int(ip)
        return any((n & mask) == net for net, mask in RFC1918_RANGES)
    except Exception:
        return False


def load_settings() -> dict:
    """Best-effort settings load without PyYAML dependency."""
    try:
        import yaml  # type: ignore
        default_path = REPO_ROOT / "config" / "settings.yml.default"
        defaults = yaml.safe_load(default_path.read_text()) or {}
        if SETTINGS_YML.exists():
            user = yaml.safe_load(SETTINGS_YML.read_text()) or {}
        else:
            user = {}

        def deep_merge(base, override):
            result = dict(base)
            for k, v in override.items():
                if k in result and isinstance(result[k], dict) and isinstance(v, dict):
                    result[k] = deep_merge(result[k], v)
                else:
                    result[k] = v
            return result

        return deep_merge(defaults, user)
    except Exception:
        return {}


def get_vm_ips(settings: dict) -> list:
    return [
        n["ip"]
        for n in settings.get("infrastructure", {}).get("nodes", [])
        if n.get("ip")
    ]


def probe_internet_rtt() -> tuple:
    """
    Returns (rtt_ms: float|None, reachable: bool).
    Uses a TCP connect to github.com:443 \u2014 no ICMP needed, works behind firewalls.
    """
    try:
        start = time.monotonic()
        s = socket.create_connection((PROBE_HOST, PROBE_PORT), timeout=PROBE_TIMEOUT_S)
        s.close()
        rtt_ms = (time.monotonic() - start) * 1000
        return round(rtt_ms, 1), True
    except OSError:
        return None, False


def get_local_cache_setting(settings: dict) -> bool:
    return bool(settings.get("optimization", {}).get("local_cache", False))


# ── Settings patching ─────────────────────────────────────────────────────────

def update_settings_local_cache(enabled: bool):
    """
    Patch (or create) config/settings.yml to set optimization.local_cache.
    Uses simple regex surgery so we preserve all comments and formatting.
    """
    value_str = "true" if enabled else "false"

    if not SETTINGS_YML.exists():
        # Create minimal override file
        SETTINGS_YML.write_text(
            f"# Generated by detect_network.py\noptimization:\n  local_cache: {value_str}\n"
        )
        return

    text = SETTINGS_YML.read_text()

    # Case 1: optimization block already exists with local_cache key
    pattern_key = r"(optimization:.*?local_cache\s*:\s*)(true|false)"
    if re.search(pattern_key, text, re.DOTALL):
        text = re.sub(pattern_key, lambda m: m.group(1) + value_str, text, flags=re.DOTALL)
        SETTINGS_YML.write_text(text)
        return

    # Case 2: optimization block exists but no local_cache key yet
    pattern_block = r"(optimization\s*:)"
    if re.search(pattern_block, text):
        text = re.sub(
            pattern_block,
            f"\\1\n  local_cache: {value_str}",
            text,
            count=1,
        )
        SETTINGS_YML.write_text(text)
        return

    # Case 3: no optimization block at all — append
    text = text.rstrip() + f"\noptimization:\n  local_cache: {value_str}\n"
    SETTINGS_YML.write_text(text)


# ── Main ──────────────────────────────────────────────────────────────────────

def main():
    # Handle --update-settings mode (called by run_all.sh after user confirms)
    if "--update-settings" in sys.argv:
        idx = sys.argv.index("--update-settings")
        if idx + 1 < len(sys.argv):
            val = sys.argv[idx + 1].lower() in ("true", "yes", "1", "y")
            update_settings_local_cache(val)
            sys.exit(0)
        else:
            print("Usage: detect_network.py --update-settings true|false", file=sys.stderr)
            sys.exit(1)

    settings    = load_settings()
    vm_ips      = get_vm_ips(settings)
    already_set = get_local_cache_setting(settings)

    # All VMs must be RFC-1918 to qualify as a LAN deployment
    all_private = all(is_rfc1918(ip) for ip in vm_ips) if vm_ips else False

    rtt_ms, reachable = probe_internet_rtt()

    if not all_private:
        reason = "VMs are on public IPs — not a local LAN deployment"
        recommend = False
    elif not reachable:
        reason = f"{PROBE_HOST} is unreachable — internet appears down or very slow"
        recommend = True
    elif rtt_ms > SLOW_THRESHOLD_MS:
        reason = f"Internet RTT to {PROBE_HOST} is {rtt_ms} ms (threshold: {SLOW_THRESHOLD_MS} ms)"
        recommend = True
    else:
        reason = f"Internet RTT to {PROBE_HOST} is {rtt_ms} ms — fast enough, caching optional"
        recommend = False

    result = {
        "is_lan":          all_private,
        "already_enabled": already_set,
        "internet_rtt_ms": rtt_ms,
        "internet_ok":     reachable,
        "recommend_cache": recommend,
        "reason":          reason,
    }

    print(json.dumps(result))


if __name__ == "__main__":
    main()
