---
- name: Wait for VMs to boot and SSH to become available
  hosts: all
  gather_facts: no
  tasks:
    - name: Wait for SSH connection to become fully available
      wait_for_connection:
        delay: 5
        timeout: 300

- name: Prep baseline system configurations and TLS credentials
  hosts: all
  gather_facts: yes
  roles:
    - cache_manager     # Download binaries once to controller when local_cache_mode=true
    - system_prep
    - tls_distributor


- name: Deploy common Hyperledger Besu configuration
  hosts: all
  gather_facts: yes
  roles:
    - besu_common

- name: Configure Validator nodes
  hosts: validators
  gather_facts: no
  roles:
    - besu_validator

- name: Configure Bootnodes
  hosts: bootnodes
  gather_facts: no
  roles:
    - besu_bootnode

- name: Configure RPC nodes
  hosts: rpc
  gather_facts: no
  roles:
    - besu_rpc

- name: Start and enable Besu service
  hosts: all
  gather_facts: no
  tasks:
    - name: Start and enable Besu service
      service:
        name: besu
        state: started
        enabled: yes
      become: yes

- name: Fetch RPC node TLS certificate to the host
  hosts: rpc
  gather_facts: no
  tasks:
    - name: Fetch node.crt from rpc-node
      fetch:
        src: /opt/besu/certs/node.crt
        dest: "{{ playbook_dir }}/../../monitoring/certs/rpc-node.crt"
        flat: yes
      become: yes
