---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: rpc-node-1
    image: debian:trixie
    command: sleep infinity
    pre_build_image: true
    groups:
      - rpc
      - all
provisioner:
  name: ansible
  env:
    ANSIBLE_ROLES_PATH: "${MOLECULE_PROJECT_DIRECTORY}/.."
    ANSIBLE_REMOTE_TMP: /tmp/.ansible/tmp
verifier:
  name: ansible
